--- 
theme: sundae
twitter_url: https://twitter.com/dharmafly
project_url: https://github.com/dharmafly/jsonpatch.js
ga_id: UA-34978047-4
future: true
project_name: jsonpatch.js
quote: 
  cite: Thomas Jefferson
  quote: The hole and the patch should be commensurate.
auto: false
lsi: false
baseurl: /
pygments: false
version: 0.0.2
download_links: 
- title: Master branch zip
  href: https://github.com/dharmafly/jsonpatch.js/zipball/master
  text: jsonpatch.js
  subtext: v{{ version }}
permalink: /:title
lang: javascript
scripts: 
safe: false
server: false
markdown: maruku
exclude: 
- README.md
- assets
- FiddlerRules.farx
sections: 
- name: Overview
  path: /index.html
- name: Reference
  path: /reference/index.html
